apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster1
  namespace: argocd
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: cowman-backend
    kind: SecretStore
  target:
    name: cluster1
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
      data:
        name: cluster1
        server: "{{ .server }}"
        config: "{{ .config }}"
  data:
  - secretKey: server
    remoteRef:
      key: 'clusters/cluster1'
      property: cluster_url

  - secretKey: config
    remoteRef:
      key: 'sre-token'
      property: config
