apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trident-secret
  namespace: trident
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: trident-secret
  data:
  - secretKey: username
    remoteRef:
      key: 'secret/trident'
      property: data
